#!/usr/bin/env bash
# Runs on EVERY container start (postStartCommand). Re-sources .env, then
# reports auth state — so a rotated Keychain value takes effect on restart
# rather than needing a full rebuild.
#
# **It reports and never fixes.** A start-up hook that silently repaired state
# would hide the thing worth knowing: which credential stopped working, and
# when. Every line below is an observation.
set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(dirname "$SCRIPT_DIR")"
ENV_FILE="$SCRIPT_DIR/.env"

# `runArgs --env-file` applies only at container create, so without this a
# rotated secret needs a rebuild. Writing a profile fragment makes every shell
# started afterwards see the same values, not only this one.
if [ -f "$ENV_FILE" ]; then
  set -a; . "$ENV_FILE"; set +a
  TMP=$(mktemp)
  cat > "$TMP" <<EOF
#!/bin/sh
# Auto-generated by .devcontainer/check-auth.sh — do not edit.
if [ -f "$ENV_FILE" ]; then set -a; . "$ENV_FILE"; set +a; fi
EOF
  sudo install -m 0644 -o root -g root "$TMP" /etc/profile.d/devcontainer-env.sh
  rm -f "$TMP"
fi

echo ""
echo "═══════════════ environment ═══════════════"

if command -v gh >/dev/null 2>&1; then
  if gh auth status &>/dev/null; then
    echo "  ✓ GitHub CLI — authenticated"
  elif [ -n "${GITHUB_TOKEN:-}" ]; then
    echo "  ✗ GitHub CLI — GITHUB_TOKEN set but rejected (expired? wrong scopes?)"
  else
    echo "  ✗ GitHub CLI — not authenticated. Run: gh auth login"
  fi
fi

if [ -n "${CLAUDE_CODE_OAUTH_TOKEN:-}" ]; then
  echo "  ✓ Claude Code — OAuth token present"
else
  echo "  ✗ Claude Code — no OAuth token. Run 'claude setup-token' on your host"
fi

# Probe each tool **the way its loci actually invoke it**, not by looking for a
# bare binary on PATH. A lockfile-sourced tool lives in the project tree and
# never on PATH — probing for the binary reported it missing on a container
# where every locus ran it fine (ADR 0020 is the same point about invocations).
#
# Add a line per tool this project's register pins. The argument list is the
# invocation, so `check_tool ruff uv run ruff` probes what pre-commit and CI
# both run.
check_tool() {
  local label="$1" out first
  shift
  if out=$(cd "$REPO_DIR" && "$@" --version 2>/dev/null); then
    first=$(printf '%s\n' "$out" | head -1)
  else
    first=""
  fi
  if [ -n "$first" ]; then
    echo "  ✓ ${label} — ${first}"
  else
    echo "  ✗ ${label} — missing (re-run: bash .devcontainer/setup.sh)"
  fi
}

check_tool claude claude
# The one tool `setup.sh` installs itself, and the one every verification in
# this standard runs through. A container reporting every credential green and
# no uv is a container in which nothing can be checked.
check_tool uv uv

# **A wired locus with no installed hook.** `.pre-commit-config.yaml` is a
# statement of intent and `.git/hooks/pre-commit` is whether anything runs, and
# every gate that declares a `pre-commit` locus reads the first. Phase 4's
# consumer repo had the config deployed, stamped, and reported wired by the
# checker, with no hook installed and every commit sailing through — because
# hooks are installed at container-create and that repo gained its lockfile
# afterwards.
#
# It is reported here rather than repaired, which is this script's rule: a
# start-up hook that silently fixed state would hide which locus stopped working
# and when. It cannot be a control either — `.git/hooks/` is untracked, and CI
# has no hooks installed and should not.
if [ -f "$REPO_DIR/.pre-commit-config.yaml" ]; then
  if [ -x "$REPO_DIR/.git/hooks/pre-commit" ]; then
    echo "  ✓ pre-commit hook — installed"
  else
    echo "  ✗ pre-commit hook — .pre-commit-config.yaml is present and"
    echo "      .git/hooks/pre-commit is not. Nothing runs at the pre-commit"
    echo "      locus. Fix: bash .devcontainer/setup.sh"
  fi
fi

# Identity may come from git config or from GIT_AUTHOR_* in the environment
# (fetch-secrets.sh supplies the latter). `git var` asks the question actually
# being asked — can git name an author? — and answers it whichever way it is set.
if ident=$(git var GIT_AUTHOR_IDENT 2>/dev/null); then
  echo "  ✓ git — ${ident% * *}"
else
  echo "  ✗ git — identity not configured"
fi

echo "═══════════════════════════════════════════"
echo ""
